version: "3.3"

services:
  app:
    image: node:19
    container_name: vote_here_api
    build:
      context: ./src
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./src:/app
    depends_on:
      - mongodb
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongodb:22011/VoteHereApi

  mongodb:
    image: mongo:5.0.7
    container_name: vote_here_api_db
    volumes:
      - ./src:/app
    restart: always
    ports:
      - "2201:2201"

networks:
  default:
    name: vote_here_api_net
